import { Theme, ThemeColors } from './types';

const baseColors = {
  classic: {
    background: '#f8fafc',
    primary: '#181d26',
    secondary: '#e0e2e6',
    accent: '#1b61c9',
    success: '#006400',
    textPrimary: '#181d26',
    textSecondary: '#333840',
    border: '#e5e7eb',
    card: '#ffffff',
    cardHover: '#f1f5f9',
    input: '#ffffff',
    inputBorder: '#d1d5db',
    buttonPrimary: '#181d26',
    buttonPrimaryHover: '#0d1218',
    buttonSecondary: '#ffffff',
    buttonSecondaryHover: '#f9fafb',
    ganttGridLine: '#e5e7eb',
    ganttToday: '#fef3c7',
    priorityHigh: '#aa2d00',
    priorityMedium: '#1b61c9',
    priorityLow: '#0a2e0e',
    statusTodo: '#6b7280',
    statusInProgress: '#1b61c9',
    statusDone: '#006400',
  } as ThemeColors,
  
  'starry-night': {
    background: '#0f172a',
    primary: '#e2e8f0',
    secondary: '#1e293b',
    accent: '#3b82f6',
    success: '#22c55e',
    textPrimary: '#f1f5f9',
    textSecondary: '#94a3b8',
    border: '#334155',
    card: '#1e293b',
    cardHover: '#334155',
    input: '#1e293b',
    inputBorder: '#475569',
    buttonPrimary: '#3b82f6',
    buttonPrimaryHover: '#2563eb',
    buttonSecondary: '#1e293b',
    buttonSecondaryHover: '#334155',
    ganttGridLine: '#334155',
    ganttToday: '#422006',
    priorityHigh: '#ef4444',
    priorityMedium: '#3b82f6',
    priorityLow: '#22c55e',
    statusTodo: '#64748b',
    statusInProgress: '#3b82f6',
    statusDone: '#22c55e',
  } as ThemeColors,
  
  aurora: {
    background: '#0a0f1a',
    primary: '#06b6d4',
    secondary: '#1e3a5f',
    accent: '#8b5cf6',
    success: '#10b981',
    textPrimary: '#f0f9ff',
    textSecondary: '#7dd3fc',
    border: '#1e40af',
    card: '#0f172a',
    cardHover: '#1e3a5f',
    input: '#0f172a',
    inputBorder: '#1e40af',
    buttonPrimary: '#8b5cf6',
    buttonPrimaryHover: '#7c3aed',
    buttonSecondary: '#1e3a5f',
    buttonSecondaryHover: '#2563eb',
    ganttGridLine: '#1e3a5f',
    ganttToday: '#422006',
    priorityHigh: '#f472b6',
    priorityMedium: '#06b6d4',
    priorityLow: '#10b981',
    statusTodo: '#64748b',
    statusInProgress: '#06b6d4',
    statusDone: '#10b981',
  } as ThemeColors,
  
  'serene-nature': {
    background: '#f0fdf4',
    primary: '#166534',
    secondary: '#dcfce7',
    accent: '#15803d',
    success: '#22c55e',
    textPrimary: '#14532d',
    textSecondary: '#4d7c0f',
    border: '#bbf7d0',
    card: '#ffffff',
    cardHover: '#dcfce7',
    input: '#ffffff',
    inputBorder: '#86efac',
    buttonPrimary: '#15803d',
    buttonPrimaryHover: '#166534',
    buttonSecondary: '#ffffff',
    buttonSecondaryHover: '#f0fdf4',
    ganttGridLine: '#bbf7d0',
    ganttToday: '#fef9c3',
    priorityHigh: '#b91c1c',
    priorityMedium: '#15803d',
    priorityLow: '#047857',
    statusTodo: '#6b7280',
    statusInProgress: '#15803d',
    statusDone: '#22c55e',
  } as ThemeColors,
  
  'energetic-coral': {
    background: '#fff7ed',
    primary: '#c2410c',
    secondary: '#fed7aa',
    accent: '#ea580c',
    success: '#16a34a',
    textPrimary: '#7c2d12',
    textSecondary: '#9a3412',
    border: '#fdba74',
    card: '#ffffff',
    cardHover: '#ffedd5',
    input: '#ffffff',
    inputBorder: '#fdba74',
    buttonPrimary: '#c2410c',
    buttonPrimaryHover: '#9a3412',
    buttonSecondary: '#ffffff',
    buttonSecondaryHover: '#fff7ed',
    ganttGridLine: '#fed7aa',
    ganttToday: '#fef9c3',
    priorityHigh: '#dc2626',
    priorityMedium: '#ea580c',
    priorityLow: '#16a34a',
    statusTodo: '#6b7280',
    statusInProgress: '#ea580c',
    statusDone: '#16a34a',
  } as ThemeColors,
  
  'glamour-pink': {
    background: '#fdf2f8',
    primary: '#be185d',
    secondary: '#fce7f3',
    accent: '#db2777',
    success: '#059669',
    textPrimary: '#831843',
    textSecondary: '#a21caf',
    border: '#f9a8d4',
    card: '#ffffff',
    cardHover: '#fdf2f8',
    input: '#ffffff',
    inputBorder: '#f9a8d4',
    buttonPrimary: '#db2777',
    buttonPrimaryHover: '#be185d',
    buttonSecondary: '#ffffff',
    buttonSecondaryHover: '#fdf2f8',
    ganttGridLine: '#f9a8d4',
    ganttToday: '#fef9c3',
    priorityHigh: '#be185d',
    priorityMedium: '#db2777',
    priorityLow: '#059669',
    statusTodo: '#6b7280',
    statusInProgress: '#db2777',
    statusDone: '#059669',
  } as ThemeColors,
  
  minimalist: {
    background: '#fafafa',
    primary: '#171717',
    secondary: '#f5f5f5',
    accent: '#404040',
    success: '#525252',
    textPrimary: '#0a0a0a',
    textSecondary: '#737373',
    border: '#d4d4d4',
    card: '#ffffff',
    cardHover: '#f5f5f5',
    input: '#ffffff',
    inputBorder: '#d4d4d4',
    buttonPrimary: '#171717',
    buttonPrimaryHover: '#0a0a0a',
    buttonSecondary: '#ffffff',
    buttonSecondaryHover: '#fafafa',
    ganttGridLine: '#e5e5e5',
    ganttToday: '#f5f5f5',
    priorityHigh: '#262626',
    priorityMedium: '#525252',
    priorityLow: '#737373',
    statusTodo: '#a3a3a3',
    statusInProgress: '#525252',
    statusDone: '#262626',
  } as ThemeColors,
};

export const themes: Theme[] = [
  {
    id: 'classic',
    name: 'Clássico',
    nameLocalizedKey: 'themes.classic',
    colors: baseColors.classic,
    isDark: false,
  },
  {
    id: 'starry-night',
    name: 'Noite Estrelada',
    nameLocalizedKey: 'themes.starryNight',
    colors: baseColors['starry-night'],
    isDark: true,
  },
  {
    id: 'aurora',
    name: 'Aurora Boreal',
    nameLocalizedKey: 'themes.aurora',
    colors: baseColors.aurora,
    isDark: true,
  },
  {
    id: 'serene-nature',
    name: 'Natureza Serena',
    nameLocalizedKey: 'themes.sereneNature',
    colors: baseColors['serene-nature'],
    isDark: false,
  },
  {
    id: 'energetic-coral',
    name: 'Coral Energético',
    nameLocalizedKey: 'themes.energeticCoral',
    colors: baseColors['energetic-coral'],
    isDark: false,
  },
  {
    id: 'glamour-pink',
    name: 'Rosa Glamour',
    nameLocalizedKey: 'themes.glamourPink',
    colors: baseColors['glamour-pink'],
    isDark: false,
  },
  {
    id: 'minimalist',
    name: 'Minimalista',
    nameLocalizedKey: 'themes.minimalist',
    colors: baseColors.minimalist,
    isDark: false,
  },
];

export const DEFAULT_THEME_ID = 'classic';

export function getThemeById(id: string): Theme {
  return themes.find(t => t.id === id) || themes[0];
}